# Generated by Django 3.2.16 on 2023-08-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230804_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
